### ISSUE TITLE
no logcat output

### ISSUE THREAD

**Issue by deechang** [guardian/toolargetool#6]
Somehow, no logcat output like
`D/TooLargeTool: MainActivity.onSaveInstanceState wrote: Bundle@200090398 contains 1 keys and measures 0.6 KB when serialized as a Parcel * android:viewHierarchyState = 0.6 KB`

is being shown in my app after adding the toolargetool as described in the readme.

I even added this code to my app:
`Intent intent = new Intent(this, ActivityB.class);
intent.putExtra("bytes", new byte[1000 * 1000]);
startActivity(intent);`

to make the app throw the TransactionTooLargeException. The Exception is indeed being thrown, but no TooLargeTool output to be found.

**Comment by maxspencer** [comment]
Hi @deechang I think this may be due to a current limitation of the tool. I figured out how to automatically log those kinds of messages when state is saved in `onSaveInstanceState`. But I'm not sure if there's a way to intercept all the intents passed to `startActivity`.

If you know which Activity/Intent it is that's causing your crash then you can log a breakdown of its extras explicitly by adding `TooLargeTool.logBundleBreakdown(intent.getExtras())` before `startActivity(intent)`.

**Comment by littlehome-eugene** [comment]
error: no suitable method found for logBundleBreakdown(Bundle)

Am I missing something?

**Comment by maxspencer** [comment]
Yes @littlehome-eugene use [`TooLargeTool.logBundleBreakdown(String tag, Bundle bundle)`](https://github.com/guardian/toolargetool/blob/master/toolargetool/src/main/java/com/gu/toolargetool/TooLargeTool.java#L38) then make sure you filter for logs using that tag (see my comment on your other issue #16).
